[package]
name = "rsevmasm"
version = "0.1.0"
authors = ["Joel Frank <joel.frank@rub.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"

[dev-dependencies]
maplit = "1.0"
